name: Upload All Music to Google Drive

on:
  push:
    paths:
      - "**/*"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload everything in the repo
        uses: vijaykramesh/google-drive-upload-git-action@v1.0.0
        with:
          credentials: ${{ secrets.GDRIVE_KEY_B64 }}
          folder: "1YXV9je0GKjoCcytKkOqKEPPUv2dnwL-E"
          target: "."  # Upload everything from root of repo