name: Upload Music with gdrive CLI

on:
  push:
    paths:
      - "**/*.mp3"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.jpeg"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google credentials
        run: |
          echo "${{ secrets.GDRIVE_KEY_B64 }}" | base64 --decode > gdrive-creds.json

      - name: Install gdrive binary from community fork
        run: |
          wget -O gdrive.zip https://github.com/tjol/gdrive/releases/download/2.1.1/gdrive-linux-x64.zip
          unzip gdrive.zip
          chmod +x gdrive
          sudo mv gdrive /usr/local/bin/gdrive

      - name: Upload files to Drive
        run: |
          mkdir -p ~/.gdrive
          cp gdrive-creds.json ~/.gdrive/token_v2.json
          gdrive about || echo "Connected!"
          for file in $(find . -type f \( -name '*.mp3' -o -name '*.jpg' -o -name '*.png' -o -name '*.jpeg' \)); do
            echo "Uploading $file"
            gdrive upload --parent 1YXV9je0GKjoCcytKkOqKEPPUv2dnwL-E "$file"
          done
