name: Upload Music with gdrive CLI

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Decode service account key
        run: |
          echo "${{ secrets.GDRIVE_KEY_B64 }}" | base64 --decode > service-account.json

      - name: Use Docker container to upload
        run: |
          docker run --rm \
            -v "$PWD:/data" \
            -v "$PWD/service-account.json:/service-account.json" \
            ghcr.io/gliderlabs/gdrive:latest \
            --service-account /service-account.json upload /data
