name: Upload Music with gdrive CLI

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up service account key
        run: |
          echo "${{ secrets.GDRIVE_KEY_B64 }}" | base64 --decode > key.json

      - name: Install gdrive CLI (verified version)
        run: |
          wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive-linux-x64 -O gdrive
          chmod +x gdrive
          sudo mv gdrive /usr/local/bin/gdrive

      - name: Upload files to Google Drive
        run: |
          mkdir -p ~/.gdrive
          gdrive --service-account key.json upload .