name: Upload All Music to Google Drive

on:
  push:
    paths:
      - "**/*"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload music to Google Drive
        uses: alemayhu/google-drive-upload@v1.0.0
        with:
          credentials: ${{ secrets.GDRIVE_KEY_B64 }}
          folderId: "1YXV9je0GKjoCcytKkOqKEPPUv2dnwL-E"
          overwrite: true
          name: "MusicUpload"
