name: Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files to Google Drive
        uses: tj-actions/gdrive@v3
        with:
          service_account_key: ${{ secrets.GDRIVE_KEY_B64 }}
          folder_id: 1YXV9je0GKjoCcytKkOqKEPPUv2dnwL-E
          files: |
            **
