name: Upload All Music to Google Drive

on:
  push:
    paths:
      - "**/*"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to Google Drive
        uses: tsu-nera/google-drive-upload-action@v1
        with:
          credentials: ${{ secrets.GDRIVE_KEY_B64 }}
          folder-id: "1YXV9je0GKjoCcytKkOqKEPPUv2dnwL-E"
          src: "."
