name: Upload Music with gdrive CLI

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Decode service account key
        run: |
          echo "${{ secrets.GDRIVE_KEY_B64 }}" | base64 --decode > service-account.json

      - name: Upload to Google Drive via Docker (gdrive-org/gdrive)
        run: |
          docker run --rm \
            -v "$PWD:/data" \
            -v "$PWD/service-account.json:/service-account.json" \
            gdrive-org/gdrive \
            --service-account /service-account.json upload /data
