name: Upload to Google Drive (via gdrive-action)

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files using gdrive-action
        uses: gsuitedevs/gdrive-action@v1
        with:
          service-account-json: ${{ secrets.GDRIVE_KEY_B64 }}
          folder-id: 1YXV9je0GKjoCcytKkOqKEPPUv2dnwL-E
          files: |
            **
